#!/bin/bash
# Quick Test Script for Add-to-Cart Functionality

echo "🧪 ADD-TO-CART TESTING GUIDE"
echo "============================"
echo ""
echo "✅ Server Status: Running on port 3000"
echo "✅ Database: MongoDB connected"
echo "✅ Fix Applied: Fabric duplicate key error handled"
echo ""
echo "📝 TEST STEPS:"
echo ""
echo "1. LOGIN"
echo "   URL: http://localhost:3000/login"
echo "   Credentials:"
echo "   - customer@designden.com / customer123"
echo "   - OR sai4@gmail.com / (your password)"
echo ""
echo "2. GO TO SHOP"
echo "   URL: http://localhost:3000/shop"
echo "   - 12 products available"
echo ""
echo "3. SELECT A PRODUCT"
echo "   - Click on any product (e.g., 'Designer Dress', 'Elegant Kurthi')"
echo ""
echo "4. CHOOSE OPTIONS"
echo "   - Select Size: M, L, or XL"
echo "   - Select Color: Black, Red, Blue, etc."
echo "   - Quantity: 1 (default)"
echo ""
echo "5. CLICK 'ADD TO CART'"
echo "   - Should redirect to cart page"
echo "   - Item should appear in cart"
echo ""
echo "6. VERIFY IN CART"
echo "   URL: http://localhost:3000/customer/cart"
echo "   - Item should be listed"
echo "   - Correct size, color, quantity"
echo "   - Price should be displayed"
echo ""
echo "✅ EXPECTED RESULT:"
echo "   - No errors in browser"
echo "   - Item successfully added to cart"
echo "   - Can proceed to checkout"
echo ""
echo "🔍 IF ISSUES OCCUR:"
echo "   Check terminal logs for:"
echo "   - [ADD-TO-CART] Request data"
echo "   - [ADD-TO-CART] Product found"
echo "   - [ADD-TO-CART] Using existing fabric"
echo "   - [ADD-TO-CART] Cart saved successfully"
echo ""
echo "📞 READY TO TEST!"
echo "============================"