name: Playwright E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Wait for MongoDB
        run: |
          for i in {1..30}; do
            if nc -z localhost 27017; then echo 'Mongo ready' && break; fi
            echo 'Waiting for Mongo...' && sleep 2
          done
      - name: Install e2e deps
        working-directory: test/e2e
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Run E2E tests
        working-directory: test/e2e
        env:
          MONGODB_URI: mongodb://localhost:27017/designden
        run: npx playwright test --reporter=list
